"""empty message

Revision ID: 3534ee9d0deb
Revises: 88b2d0066862
Create Date: 2017-12-08 11:13:41.460732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3534ee9d0deb'
down_revision = '88b2d0066862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ltesighting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensor_id', sa.Text(), nullable=True),
    sa.Column('imsi_hash', sa.Text(), nullable=True),
    sa.Column('hplmn_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ltesighting')
    # ### end Alembic commands ###
