"""empty message

Revision ID: 3c1de29f174c
Revises: 3534ee9d0deb
Create Date: 2017-12-08 11:23:46.213248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1de29f174c'
down_revision = '3534ee9d0deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('sensors', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('sensors', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('sensors', 'lng')
    op.drop_column('sensors', 'lat')
    # ### end Alembic commands ###
