"""empty message

Revision ID: 4d60572e15d7
Revises: 7da76dda6fcc
Create Date: 2018-01-29 15:41:26.701772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d60572e15d7'
down_revision = '7da76dda6fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journeys', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journeys', 'data')
    # ### end Alembic commands ###
