"""empty message

Revision ID: 4df2fcbbc0b5
Revises: 4a64777d3334
Create Date: 2017-12-06 13:39:55.011572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4df2fcbbc0b5'
down_revision = '4a64777d3334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('coords', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'coords')
    # ### end Alembic commands ###
