"""empty message

Revision ID: 7da76dda6fcc
Revises: 
Create Date: 2018-01-29 15:24:12.023478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7da76dda6fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('geodata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basehandsetsightings',
    sa.Column('roundedtohour', sa.DateTime(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('roundedtoday', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('roundedtohour', 'network', 'country')
    )
    op.create_table('dates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('_from', sa.Date(), nullable=True),
    sa.Column('_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journeys',
    sa.Column('origin_id', sa.String(length=255), nullable=False),
    sa.Column('destination_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('origin_id', 'destination_id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcc_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('mnc_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sightingsperhourpercountry',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('country', 'hour')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uniquecountryhandsetsightings',
    sa.Column('day', sa.DateTime(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('day', 'network', 'country')
    )
    op.create_table('smallcells',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ltesighting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('smallcell_id', sa.Text(), nullable=True),
    sa.Column('imsi_hash', sa.Text(), nullable=True),
    sa.Column('hplmn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hplmn_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['smallcell_id'], ['smallcells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_day_sighting_wide',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_sighting', sa.DateTime(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('age_range', sa.Text(), nullable=True),
    sa.Column('continent_name', sa.Text(), nullable=True),
    sa.Column('handset_make_name', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.Text(), nullable=True),
    sa.Column('home_ps_area_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['smallcells.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'first_sighting')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_day_sighting_wide')
    op.drop_table('ltesighting')
    op.drop_table('smallcells')
    op.drop_table('uniquecountryhandsetsightings')
    op.drop_table('sites')
    op.drop_table('sightingsperhourpercountry')
    op.drop_table('networks')
    op.drop_table('journeys')
    op.drop_table('department')
    op.drop_table('dates')
    op.drop_table('basehandsetsightings')
    op.drop_table('areas')
    # ### end Alembic commands ###
