"""empty message

Revision ID: 88b2d0066862
Revises: 4df2fcbbc0b5
Create Date: 2017-12-08 10:05:29.422828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88b2d0066862'
down_revision = '4df2fcbbc0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lte_sightings')
    op.drop_table('bucketlists')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bucketlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='bucketlists_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='bucketlists_pkey')
    )
    op.create_table('lte_sightings',
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sensor_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salt_context_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hash_imsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hplmn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rsrp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rsrq', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bgimsi', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('sites')
    op.drop_table('sensors')
    # ### end Alembic commands ###
